# Generated by Django 5.2.12 on 2026-03-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0003_footerlink_homepage_instructor_leadershipmember_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Instructor",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("full_name", models.CharField(max_length=160, verbose_name="Име")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("role_title", models.CharField(max_length=160, verbose_name="Роля")),
                        ("biography", models.TextField(verbose_name="Биография")),
                        ("credentials", models.TextField(blank=True, verbose_name="Квалификации")),
                        ("portrait", models.ImageField(blank=True, null=True, upload_to="instructors/", verbose_name="Портрет")),
                        ("email", models.EmailField(blank=True, max_length=254, verbose_name="Имейл")),
                        ("phone", models.CharField(blank=True, max_length=64, verbose_name="Телефон")),
                    ],
                    options={
                        "verbose_name": "Преподавател",
                        "verbose_name_plural": "Преподаватели",
                        "db_table": "cms_instructor",
                        "ordering": ["sort_order", "full_name"],
                    },
                ),
                migrations.CreateModel(
                    name="ProgramCategory",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("name", models.CharField(max_length=120, verbose_name="Име")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("description", models.TextField(blank=True, verbose_name="Описание")),
                    ],
                    options={
                        "verbose_name": "Категория програми",
                        "verbose_name_plural": "Категории програми",
                        "db_table": "cms_programcategory",
                        "ordering": ["sort_order", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="Program",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("title", models.CharField(max_length=160, verbose_name="Заглавие")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("summary", models.TextField(verbose_name="Кратко описание")),
                        ("description", models.TextField(verbose_name="Подробно описание")),
                        ("audience", models.CharField(blank=True, max_length=160, verbose_name="Подходящо за")),
                        ("duration", models.CharField(blank=True, max_length=120, verbose_name="Продължителност")),
                        ("age_group", models.CharField(blank=True, max_length=120, verbose_name="Възрастова група")),
                        ("level", models.CharField(blank=True, max_length=120, verbose_name="Ниво")),
                        ("location_name", models.CharField(blank=True, max_length=160, verbose_name="Локация")),
                        ("inquiry_email", models.EmailField(blank=True, max_length=254, verbose_name="Имейл за записване")),
                        ("cta_label", models.CharField(default="Изпрати запитване", max_length=80, verbose_name="Текст на бутона")),
                        ("cover_image", models.ImageField(blank=True, null=True, upload_to="programs/", verbose_name="Основно изображение")),
                        ("is_featured", models.BooleanField(default=True, verbose_name="Показвай на началната страница")),
                        ("instructors", models.ManyToManyField(blank=True, db_table="cms_program_instructors", related_name="programs", to="programs.instructor", verbose_name="Преподаватели")),
                        ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="programs", to="programs.programcategory", verbose_name="Категория")),
                    ],
                    options={
                        "verbose_name": "Програма",
                        "verbose_name_plural": "Програми",
                        "db_table": "cms_program",
                        "ordering": ["sort_order", "title"],
                    },
                ),
                migrations.CreateModel(
                    name="PricingBlock",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("title", models.CharField(max_length=120, verbose_name="План")),
                        ("price_label", models.CharField(max_length=64, verbose_name="Цена")),
                        ("billing_period", models.CharField(blank=True, max_length=120, verbose_name="Период")),
                        ("description", models.TextField(blank=True, verbose_name="Описание")),
                        ("is_featured", models.BooleanField(default=False, verbose_name="Подчертай")),
                        ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pricing_options", to="programs.program")),
                    ],
                    options={
                        "verbose_name": "Ценови блок",
                        "verbose_name_plural": "Ценови блокове",
                        "db_table": "cms_programpricing",
                        "ordering": ["sort_order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="ProgramGalleryImage",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("image", models.ImageField(upload_to="program_gallery/", verbose_name="Изображение")),
                        ("caption", models.CharField(blank=True, max_length=220, verbose_name="Надпис")),
                        ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gallery_items", to="programs.program")),
                    ],
                    options={
                        "verbose_name": "Снимка от програмна галерия",
                        "verbose_name_plural": "Програмни галерии",
                        "db_table": "cms_programgalleryimage",
                        "ordering": ["sort_order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="ProgramSchedule",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("title", models.CharField(blank=True, max_length=120, verbose_name="Етикет")),
                        ("day_label", models.CharField(max_length=64, verbose_name="Ден")),
                        ("start_time", models.TimeField(verbose_name="Начало")),
                        ("end_time", models.TimeField(verbose_name="Край")),
                        ("room", models.CharField(blank=True, max_length=120, verbose_name="Зала или локация")),
                        ("notes", models.CharField(blank=True, max_length=220, verbose_name="Бележка")),
                        ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="schedule_entries", to="programs.program")),
                    ],
                    options={
                        "verbose_name": "График",
                        "verbose_name_plural": "Графици",
                        "db_table": "cms_programschedule",
                        "ordering": ["sort_order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="ProgramSession",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("title", models.CharField(max_length=255, verbose_name="Заглавие")),
                        ("date", models.DateField(verbose_name="Дата")),
                        ("time", models.TimeField(verbose_name="Начало")),
                        ("description", models.TextField(blank=True, verbose_name="Описание")),
                        ("category", models.CharField(blank=True, max_length=120, verbose_name="Етикет")),
                        ("image", models.ImageField(blank=True, help_text="Качете файл от компютъра си.", null=True, upload_to="events/", verbose_name="Изображение")),
                        ("attendees", models.PositiveIntegerField(default=0, verbose_name="Участници")),
                    ],
                    options={
                        "verbose_name": "Сесия или събитие",
                        "verbose_name_plural": "Сесии и събития",
                        "db_table": "cms_event",
                        "ordering": ["date", "time"],
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name="programcategory",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Публикувано"),
        ),
        migrations.AddField(
            model_name="programcategory",
            name="seo_title",
            field=models.CharField(blank=True, help_text="По желание заменя стандартното заглавие в търсачки и споделяне.", max_length=160, verbose_name="SEO заглавие"),
        ),
        migrations.AddField(
            model_name="programcategory",
            name="seo_description",
            field=models.TextField(blank=True, help_text="Кратко описание за търсачки, социални мрежи и линк превюта.", verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="programcategory",
            name="seo_image",
            field=models.ImageField(blank=True, help_text="Използва се при споделяне в социални мрежи, когато има нужда от отделно изображение.", null=True, upload_to="seo/", verbose_name="SEO изображение"),
        ),
        migrations.AddField(
            model_name="program",
            name="seo_title",
            field=models.CharField(blank=True, help_text="По желание заменя стандартното заглавие в търсачки и споделяне.", max_length=160, verbose_name="SEO заглавие"),
        ),
        migrations.AddField(
            model_name="program",
            name="seo_description",
            field=models.TextField(blank=True, help_text="Кратко описание за търсачки, социални мрежи и линк превюта.", verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="program",
            name="seo_image",
            field=models.ImageField(blank=True, help_text="Използва се при споделяне в социални мрежи, когато има нужда от отделно изображение.", null=True, upload_to="seo/", verbose_name="SEO изображение"),
        ),
        migrations.AddField(
            model_name="programgalleryimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=220, verbose_name="Alt текст"),
        ),
        migrations.AddField(
            model_name="programsession",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ред"),
        ),
        migrations.AddField(
            model_name="programsession",
            name="end_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Край"),
        ),
        migrations.AddField(
            model_name="programsession",
            name="location_name",
            field=models.CharField(blank=True, max_length=160, verbose_name="Локация"),
        ),
        migrations.AddField(
            model_name="programsession",
            name="program",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sessions", to="programs.program", verbose_name="Програма"),
        ),
        migrations.AlterModelOptions(
            name="programsession",
            options={
                "verbose_name": "Сесия или събитие",
                "verbose_name_plural": "Сесии и събития",
                "db_table": "cms_event",
                "ordering": ["date", "time", "sort_order"],
            },
        ),
    ]
