# Generated by Django 5.2.12 on 2026-04-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='inquiry_phone',
            field=models.CharField(blank=True, help_text='Оставете празно, за да се използва основният телефон от глобалните настройки.', max_length=64, verbose_name='Телефон за записване'),
        ),
    ]
