# Generated by Django 5.2.12 on 2026-04-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_program_inquiry_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['sort_order', 'title'], 'verbose_name': 'Школа', 'verbose_name_plural': 'Школи'},
        ),
        migrations.AlterModelOptions(
            name='programcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория школи', 'verbose_name_plural': 'Категории школи'},
        ),
        migrations.AlterModelOptions(
            name='programgalleryimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Снимка от галерия на школа', 'verbose_name_plural': 'Галерии на школи'},
        ),
        migrations.AlterField(
            model_name='programsession',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='programs.program', verbose_name='Школа'),
        ),
    ]
