# Generated by Django 5.2.12 on 2026-04-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_program_options_alter_programcategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programgalleryimage',
            name='alt_text',
        ),
    ]
