# Generated by Django 5.2.12 on 2026-03-28 17:21

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_board_member_slugs(apps, schema_editor):
    BoardMember = apps.get_model("pages", "BoardMember")
    used = set(BoardMember.objects.exclude(slug__isnull=True).exclude(slug="").values_list("slug", flat=True))

    for member in BoardMember.objects.all().order_by("pk"):
        if member.slug:
            continue

        base_slug = slugify(member.full_name) or f"board-member-{member.pk}"
        slug = base_slug
        index = 2
        while slug in used:
            slug = f"{base_slug}-{index}"
            index += 1

        member.slug = slug
        member.save(update_fields=["slug"])
        used.add(slug)


def normalize_page_data(apps, schema_editor):
    Page = apps.get_model("pages", "Page")

    Page.objects.filter(page_type="generic").update(page_type="standard")

    leadership_page = Page.objects.filter(slug="leadership").first()
    board_page = Page.objects.filter(slug="board").first()
    if leadership_page and not board_page:
        leadership_page.slug = "board"
        leadership_page.page_type = "governance"
        leadership_page.save(update_fields=["slug", "page_type"])
    else:
        Page.objects.filter(slug__in=["board", "leadership"]).update(page_type="governance")

    Page.objects.filter(slug__in=["charter", "privacy", "cookies", "history"]).update(show_in_footer=True)
    Page.objects.filter(slug__in=["membership", "board"]).update(show_in_header=True)

    sort_orders = {
        "history": 1,
        "charter": 2,
        "membership": 3,
        "board": 4,
        "privacy": 5,
        "cookies": 6,
    }
    for slug, order in sort_orders.items():
        Page.objects.filter(slug=slug).update(sort_order=order)

    for page in Page.objects.filter(navigation_title=""):
        page.navigation_title = page.title
        page.save(update_fields=["navigation_title"])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0003_footerlink_homepage_instructor_leadershipmember_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="BoardMember",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("full_name", models.CharField(max_length=160, verbose_name="Име")),
                        ("role", models.CharField(max_length=160, verbose_name="Роля")),
                        ("short_bio", models.TextField(blank=True, verbose_name="Кратка биография")),
                        ("portrait", models.ImageField(blank=True, null=True, upload_to="leadership/", verbose_name="Портрет")),
                        ("email", models.EmailField(blank=True, max_length=254, verbose_name="Имейл")),
                        ("term_label", models.CharField(blank=True, max_length=120, verbose_name="Мандат или период")),
                    ],
                    options={
                        "verbose_name": "Член на настоятелството",
                        "verbose_name_plural": "Настоятелство и екип",
                        "db_table": "cms_leadershipmember",
                        "ordering": ["sort_order", "full_name"],
                    },
                ),
                migrations.CreateModel(
                    name="GalleryImage",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("image", models.ImageField(help_text="Качете файл от компютъра си.", upload_to="gallery/", verbose_name="Изображение")),
                        ("caption", models.CharField(blank=True, max_length=500, verbose_name="Надпис")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        "verbose_name": "Снимка от галерията",
                        "verbose_name_plural": "Галерия",
                        "db_table": "cms_galleryimage",
                        "ordering": ["sort_order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="HistoryEntry",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("title", models.CharField(max_length=180, verbose_name="Заглавие")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("period_label", models.CharField(blank=True, max_length=80, verbose_name="Период")),
                        ("summary", models.TextField(blank=True, verbose_name="Кратко резюме")),
                        ("body", models.TextField(blank=True, verbose_name="Съдържание")),
                        ("image", models.ImageField(blank=True, null=True, upload_to="history/", verbose_name="Изображение")),
                    ],
                    options={
                        "verbose_name": "Исторически запис",
                        "verbose_name_plural": "История",
                        "ordering": ["sort_order", "title"],
                    },
                ),
                migrations.CreateModel(
                    name="HomePage",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("hero_badge", models.CharField(default="ОТВОРЕНО ЗА ЦЯЛОТО СЕМЕЙСТВО", max_length=120, verbose_name="Бадж в хедъра")),
                        ("hero_title", models.CharField(default="Съвременна читалищна платформа за изкуство, обучение и общност.", max_length=220, verbose_name="Основно заглавие")),
                        ("hero_body", models.TextField(default="Оригинална примерна начална страница, която показва как могат да се подредят програми, новини, контакти и записвания чрез Django админ.", verbose_name="Текст в хедъра")),
                        ("primary_cta_label", models.CharField(default="Разгледайте програмите", max_length=80, verbose_name="Основен бутон")),
                        ("primary_cta_url", models.CharField(default="/programs/", max_length=220, verbose_name="Адрес на основния бутон")),
                        ("secondary_cta_label", models.CharField(default="Проекти и новини", max_length=80, verbose_name="Втори бутон")),
                        ("secondary_cta_url", models.CharField(default="/projects/", max_length=220, verbose_name="Адрес на втория бутон")),
                        ("mission_title", models.CharField(default="Какво изграждаме", max_length=160, verbose_name="Заглавие на мисията")),
                        ("mission_body", models.TextField(default="Място за обучение, сцена за местни проекти и достъпна културна услуга за деца, младежи и възрастни.", verbose_name="Текст за мисията")),
                        ("programs_heading", models.CharField(default="Школи и клубове", max_length=160, verbose_name="Заглавие на програмите")),
                        ("programs_intro", models.TextField(default="Организирайте програмите по категории, преподаватели, графици и ценови планове.", verbose_name="Увод към програмите")),
                        ("stories_heading", models.CharField(db_column="projects_heading", default="Проекти и новини", max_length=160, verbose_name="Заглавие на публикациите")),
                        ("stories_intro", models.TextField(db_column="projects_intro", default="Публикувайте архив, активни инициативи и приложения към всяка публикация.", verbose_name="Увод към публикациите")),
                    ],
                    options={
                        "verbose_name": "Начална страница",
                        "verbose_name_plural": "Начална страница",
                        "db_table": "cms_homepage",
                    },
                ),
                migrations.CreateModel(
                    name="Page",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("page_type", models.CharField(choices=[("standard", "Стандартна страница"), ("history", "История"), ("governance", "Настоятелство и екип"), ("membership", "Членство"), ("charter", "Устав"), ("privacy", "Поверителност"), ("cookies", "Бисквитки")], default="standard", max_length=16, verbose_name="Тип")),
                        ("title", models.CharField(max_length=180, verbose_name="Заглавие")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("intro", models.TextField(blank=True, verbose_name="Увод")),
                        ("body", models.TextField(verbose_name="Съдържание")),
                        ("callout_title", models.CharField(blank=True, max_length=180, verbose_name="Заглавие на акцент")),
                        ("callout_body", models.TextField(blank=True, verbose_name="Текст на акцент")),
                    ],
                    options={
                        "verbose_name": "Страница",
                        "verbose_name_plural": "Страници",
                        "db_table": "cms_staticpage",
                        "ordering": ["sort_order", "title"],
                    },
                ),
                migrations.CreateModel(
                    name="HomeMetric",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("value", models.CharField(max_length=32, verbose_name="Стойност")),
                        ("label", models.CharField(max_length=120, verbose_name="Етикет")),
                        ("description", models.CharField(blank=True, max_length=220, verbose_name="Описание")),
                        ("home_page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stats", to="pages.homepage")),
                    ],
                    options={
                        "verbose_name": "Метрика на началната страница",
                        "verbose_name_plural": "Метрики на началната страница",
                        "db_table": "cms_homestat",
                        "ordering": ["sort_order", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="HomeFeature",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("eyebrow", models.CharField(blank=True, max_length=64, verbose_name="Кратък надпис")),
                        ("title", models.CharField(max_length=120, verbose_name="Заглавие")),
                        ("description", models.TextField(verbose_name="Описание")),
                        ("home_page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="features", to="pages.homepage")),
                    ],
                    options={
                        "verbose_name": "Акцент на началната страница",
                        "verbose_name_plural": "Акценти на началната страница",
                        "db_table": "cms_homefeature",
                        "ordering": ["sort_order", "id"],
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_title",
            field=models.CharField(blank=True, help_text="По желание заменя стандартното заглавие в търсачки и споделяне.", max_length=160, verbose_name="SEO заглавие"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_description",
            field=models.TextField(blank=True, help_text="Кратко описание за търсачки, социални мрежи и линк превюта.", verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_image",
            field=models.ImageField(blank=True, help_text="Използва се при споделяне в социални мрежи, когато има нужда от отделно изображение.", null=True, upload_to="seo/", verbose_name="SEO изображение"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contacts_heading",
            field=models.CharField(blank=True, max_length=160, verbose_name="Заглавие на контактната секция"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="contacts_intro",
            field=models.TextField(blank=True, verbose_name="Увод към контактната секция"),
        ),
        migrations.AddField(
            model_name="page",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ред"),
        ),
        migrations.AddField(
            model_name="page",
            name="navigation_title",
            field=models.CharField(blank=True, max_length=80, verbose_name="Кратко заглавие в навигацията"),
        ),
        migrations.AddField(
            model_name="page",
            name="show_in_header",
            field=models.BooleanField(default=False, verbose_name="Показвай в главното меню"),
        ),
        migrations.AddField(
            model_name="page",
            name="show_in_footer",
            field=models.BooleanField(default=False, verbose_name="Показвай във футъра"),
        ),
        migrations.AddField(
            model_name="page",
            name="seo_title",
            field=models.CharField(blank=True, help_text="По желание заменя стандартното заглавие в търсачки и споделяне.", max_length=160, verbose_name="SEO заглавие"),
        ),
        migrations.AddField(
            model_name="page",
            name="seo_description",
            field=models.TextField(blank=True, help_text="Кратко описание за търсачки, социални мрежи и линк превюта.", verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="page",
            name="seo_image",
            field=models.ImageField(blank=True, help_text="Използва се при споделяне в социални мрежи, когато има нужда от отделно изображение.", null=True, upload_to="seo/", verbose_name="SEO изображение"),
        ),
        migrations.AddField(
            model_name="boardmember",
            name="biography",
            field=models.TextField(blank=True, verbose_name="Подробна биография"),
        ),
        migrations.AddField(
            model_name="boardmember",
            name="slug",
            field=models.SlugField(blank=True, null=True, verbose_name="Кратък адрес"),
        ),
        migrations.RunPython(populate_board_member_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="boardmember",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Кратък адрес"),
        ),
        migrations.AddField(
            model_name="galleryimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=220, verbose_name="Alt текст"),
        ),
        migrations.RunPython(normalize_page_data, migrations.RunPython.noop),
    ]
