# Generated by Django 5.2.12 on 2026-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.CreateModel(
                    name="HistoryEntry",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("title", models.CharField(max_length=180, verbose_name="Заглавие")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("period_label", models.CharField(blank=True, max_length=80, verbose_name="Период")),
                        ("summary", models.TextField(blank=True, verbose_name="Кратко резюме")),
                        ("body", models.TextField(blank=True, verbose_name="Съдържание")),
                        ("image", models.ImageField(blank=True, null=True, upload_to="history/", verbose_name="Изображение")),
                    ],
                    options={
                        "verbose_name": "Исторически запис",
                        "verbose_name_plural": "История",
                        "ordering": ["sort_order", "title"],
                    },
                ),
            ],
            state_operations=[],
        ),
    ]
