# Generated by Django 5.2.12 on 2026-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_create_historyentry_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_body',
            field=models.TextField(default='Публична начална страница за програми, новини, контакти и записвания, която може да се поддържа изцяло от администрацията.', verbose_name='Текст в хедъра'),
        ),
    ]
