# Generated by Codex on 2026-04-05

import django.db.models.deletion
from django.db import migrations, models


def attach_history_entries_to_history_page(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    HistoryEntry = apps.get_model("pages", "HistoryEntry")

    history_page = Page.objects.filter(slug="history").first()
    if history_page is None and HistoryEntry.objects.exists():
        history_page = Page.objects.create(
            page_type="history",
            title="История",
            navigation_title="История",
            slug="history",
            intro="",
            body="",
            callout_title="",
            callout_body="",
            is_published=True,
            show_in_header=False,
            show_in_footer=True,
            sort_order=1,
        )

    if history_page is not None:
        HistoryEntry.objects.filter(page__isnull=True).update(page=history_page)


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_homepage_hero_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="historyentry",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_entries",
                to="pages.page",
                verbose_name="Страница",
            ),
        ),
        migrations.AlterField(
            model_name="historyentry",
            name="slug",
            field=models.SlugField(blank=True, unique=True, verbose_name="Кратък адрес"),
        ),
        migrations.RunPython(attach_history_entries_to_history_page, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historyentry",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_entries",
                to="pages.page",
                verbose_name="Страница",
            ),
        ),
    ]
