# Generated by Django 5.2.12 on 2026-04-18 19:15

import django.db.models.deletion
from django.db import migrations, models


def update_default_library_sections(apps, schema_editor):
    Page = apps.get_model("pages", "Page")
    Page.objects.filter(
        slug="library",
        callout_title__in=["", "Как да използвате страницата", "Редакционен ориентир"],
    ).update(
        callout_title="Работно време",
        callout_body="Понеделник - петък: 09:00 - 18:00\nСъбота и неделя: почивни дни",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_update_news_section_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ред')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикувано')),
                ('image', models.ImageField(upload_to='library/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=220, verbose_name='Надпис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_images', to='pages.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Снимка към библиотеката',
                'verbose_name_plural': 'Снимки към библиотеката',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(update_default_library_sections, migrations.RunPython.noop),
    ]
