# Generated by Django 5.2.12 on 2026-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заглавие')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Час')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(max_length=120, verbose_name='Категория')),
                ('category_color', models.CharField(default='primary-fixed', help_text='Напр. primary-fixed, secondary-fixed (клас без bg-).', max_length=64, verbose_name='Tailwind: цвят на категорията')),
                ('category_text_color', models.CharField(default='on-primary-fixed', help_text='Напр. on-primary-fixed.', max_length=64, verbose_name='Tailwind: цвят на текста')),
                ('image', models.URLField(blank=True, max_length=2000, verbose_name='URL на изображение')),
                ('attendees', models.PositiveIntegerField(default=0, verbose_name='Участници')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикувано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Събитие',
                'verbose_name_plural': 'Събития',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=2000, verbose_name='URL на изображение')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Надпис')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ред')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикувано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Снимка от галерията',
                'verbose_name_plural': 'Галерия',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
