# Generated by Django 5.2.12 on 2026-03-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Качете файл от компютъра си.', null=True, upload_to='events/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='Качете файл от компютъра си.', upload_to='gallery/', verbose_name='Изображение'),
        ),
    ]
