# Generated by Django 5.2.12 on 2026-03-28 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("pages", "0001_initial"),
        ("programs", "0001_initial"),
        ("stories", "0001_initial"),
        ("inquiries", "0001_initial"),
        ("cms", "0003_footerlink_homepage_instructor_leadershipmember_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="Event",
                ),
                migrations.DeleteModel(
                    name="FooterLink",
                ),
                migrations.DeleteModel(
                    name="GalleryImage",
                ),
                migrations.RemoveField(
                    model_name="homefeature",
                    name="home_page",
                ),
                migrations.RemoveField(
                    model_name="homestat",
                    name="home_page",
                ),
                migrations.RemoveField(
                    model_name="inquirysubmission",
                    name="location",
                ),
                migrations.RemoveField(
                    model_name="inquirysubmission",
                    name="program",
                ),
                migrations.RemoveField(
                    model_name="program",
                    name="instructors",
                ),
                migrations.DeleteModel(
                    name="LeadershipMember",
                ),
                migrations.RemoveField(
                    model_name="locationhour",
                    name="location",
                ),
                migrations.AlterUniqueTogether(
                    name="locationhour",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="program",
                    name="category",
                ),
                migrations.RemoveField(
                    model_name="programgalleryimage",
                    name="program",
                ),
                migrations.RemoveField(
                    model_name="programpricing",
                    name="program",
                ),
                migrations.RemoveField(
                    model_name="programschedule",
                    name="program",
                ),
                migrations.RemoveField(
                    model_name="projectattachment",
                    name="project",
                ),
                migrations.DeleteModel(
                    name="SiteSettings",
                ),
                migrations.DeleteModel(
                    name="StaticPage",
                ),
                migrations.DeleteModel(
                    name="HomeFeature",
                ),
                migrations.DeleteModel(
                    name="HomePage",
                ),
                migrations.DeleteModel(
                    name="HomeStat",
                ),
                migrations.DeleteModel(
                    name="InquirySubmission",
                ),
                migrations.DeleteModel(
                    name="Instructor",
                ),
                migrations.DeleteModel(
                    name="Location",
                ),
                migrations.DeleteModel(
                    name="LocationHour",
                ),
                migrations.DeleteModel(
                    name="ProgramCategory",
                ),
                migrations.DeleteModel(
                    name="ProgramGalleryImage",
                ),
                migrations.DeleteModel(
                    name="ProgramPricing",
                ),
                migrations.DeleteModel(
                    name="Program",
                ),
                migrations.DeleteModel(
                    name="ProgramSchedule",
                ),
                migrations.DeleteModel(
                    name="Project",
                ),
                migrations.DeleteModel(
                    name="ProjectAttachment",
                ),
            ],
        ),
    ]
