# Generated by Django 5.2.12 on 2026-03-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0003_footerlink_homepage_instructor_leadershipmember_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Story",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("story_type", models.CharField(choices=[("story", "История"), ("project", "Проект"), ("news", "Новина")], db_column="project_type", default="project", max_length=16, verbose_name="Тип")),
                        ("title", models.CharField(max_length=180, verbose_name="Заглавие")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("excerpt", models.TextField(verbose_name="Кратко резюме")),
                        ("body", models.TextField(verbose_name="Съдържание")),
                        ("cover_image", models.ImageField(blank=True, null=True, upload_to="projects/", verbose_name="Изображение")),
                        ("published_at", models.DateField(verbose_name="Дата на публикуване")),
                        ("is_featured", models.BooleanField(default=True, verbose_name="Показвай на началната страница")),
                    ],
                    options={
                        "verbose_name": "Публикация",
                        "verbose_name_plural": "Публикации",
                        "db_table": "cms_project",
                        "ordering": ["-published_at", "-id"],
                    },
                ),
                migrations.CreateModel(
                    name="StoryAttachment",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("title", models.CharField(max_length=180, verbose_name="Заглавие")),
                        ("file", models.FileField(blank=True, null=True, upload_to="project_attachments/", verbose_name="Файл")),
                        ("external_url", models.URLField(blank=True, verbose_name="Външен адрес")),
                        ("story", models.ForeignKey(db_column="project_id", on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="stories.story")),
                    ],
                    options={
                        "verbose_name": "Файл към публикация",
                        "verbose_name_plural": "Файлове към публикации",
                        "db_table": "cms_projectattachment",
                        "ordering": ["sort_order", "id"],
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name="story",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Ред"),
        ),
        migrations.AddField(
            model_name="story",
            name="seo_title",
            field=models.CharField(blank=True, help_text="По желание заменя стандартното заглавие в търсачки и споделяне.", max_length=160, verbose_name="SEO заглавие"),
        ),
        migrations.AddField(
            model_name="story",
            name="seo_description",
            field=models.TextField(blank=True, help_text="Кратко описание за търсачки, социални мрежи и линк превюта.", verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="story",
            name="seo_image",
            field=models.ImageField(blank=True, help_text="Използва се при споделяне в социални мрежи, когато има нужда от отделно изображение.", null=True, upload_to="seo/", verbose_name="SEO изображение"),
        ),
        migrations.AddField(
            model_name="storyattachment",
            name="description",
            field=models.CharField(blank=True, max_length=220, verbose_name="Описание"),
        ),
        migrations.AlterModelOptions(
            name="story",
            options={
                "verbose_name": "Публикация",
                "verbose_name_plural": "Публикации",
                "db_table": "cms_project",
                "ordering": ["sort_order", "-published_at", "-id"],
            },
        ),
    ]
