# Generated by Django 5.2.12 on 2026-03-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0003_footerlink_homepage_instructor_leadershipmember_and_more"),
        ("core", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="InquirySubmission",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("inquiry_type", models.CharField(choices=[("general", "Общо запитване"), ("enrollment", "Записване"), ("partnership", "Партньорство"), ("media", "Медийно запитване")], default="general", max_length=16, verbose_name="Вид")),
                        ("full_name", models.CharField(max_length=160, verbose_name="Име")),
                        ("email", models.EmailField(max_length=254, verbose_name="Имейл")),
                        ("phone", models.CharField(blank=True, max_length=64, verbose_name="Телефон")),
                        ("subject", models.CharField(max_length=180, verbose_name="Тема")),
                        ("message", models.TextField(verbose_name="Съобщение")),
                        ("status", models.CharField(choices=[("new", "Ново"), ("reviewed", "Прегледано"), ("closed", "Приключено")], default="new", max_length=16, verbose_name="Статус")),
                        ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inquiries", to="core.location", verbose_name="Локация")),
                        ("program", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="inquiries", to="programs.program", verbose_name="Програма")),
                    ],
                    options={
                        "verbose_name": "Запитване",
                        "verbose_name_plural": "Запитвания",
                        "db_table": "cms_inquirysubmission",
                        "ordering": ["-created_at", "-id"],
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name="inquirysubmission",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="Вътрешни бележки"),
        ),
    ]
