# Generated by Django 5.2.12 on 2026-04-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
        ('programs', '0003_alter_program_options_alter_programcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirysubmission',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='programs.program', verbose_name='Школа'),
        ),
    ]
