# Generated by Django 5.2.12 on 2026-04-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_alter_inquirysubmission_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquirysubmission',
            name='location',
        ),
    ]
