# Generated by Django 5.2.12 on 2026-03-28 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0003_footerlink_homepage_instructor_leadershipmember_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="FooterLink",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("title", models.CharField(max_length=120, verbose_name="Етикет")),
                        ("url", models.CharField(max_length=220, verbose_name="Адрес")),
                        ("open_in_new_tab", models.BooleanField(default=False, verbose_name="Отвори в нов прозорец")),
                    ],
                    options={
                        "verbose_name": "Връзка във футъра",
                        "verbose_name_plural": "Връзки във футъра",
                        "db_table": "cms_footerlink",
                        "ordering": ["sort_order", "title", "id"],
                    },
                ),
                migrations.CreateModel(
                    name="Location",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Ред")),
                        ("is_published", models.BooleanField(default=True, verbose_name="Публикувано")),
                        ("name", models.CharField(max_length=160, verbose_name="Име")),
                        ("slug", models.SlugField(unique=True, verbose_name="Кратък адрес")),
                        ("short_description", models.TextField(blank=True, verbose_name="Кратко описание")),
                        ("address_line", models.CharField(max_length=220, verbose_name="Адрес")),
                        ("city", models.CharField(default="София", max_length=120, verbose_name="Град")),
                        ("postal_code", models.CharField(blank=True, max_length=20, verbose_name="Пощенски код")),
                        ("phone", models.CharField(blank=True, max_length=64, verbose_name="Телефон")),
                        ("email", models.EmailField(blank=True, max_length=254, verbose_name="Имейл")),
                        ("map_embed_url", models.URLField(blank=True, verbose_name="Карта")),
                        ("access_notes", models.TextField(blank=True, verbose_name="Допълнителна информация")),
                        ("is_primary", models.BooleanField(default=False, verbose_name="Основна локация")),
                    ],
                    options={
                        "verbose_name": "Локация",
                        "verbose_name_plural": "Локации",
                        "db_table": "cms_location",
                        "ordering": ["-is_primary", "sort_order", "name"],
                    },
                ),
                migrations.CreateModel(
                    name="SiteSettings",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                        ("site_name", models.CharField(default="Chitalishte Connect", max_length=160, verbose_name="Име на сайта")),
                        ("site_tagline", models.CharField(default="Културни програми, общност и съвременни читалищни услуги.", max_length=220, verbose_name="Кратък слоган")),
                        ("footer_summary", models.TextField(blank=True, default="Примерно съдържание за културен център. Заменете го от администрацията с реалните текстове, контакти и правни страници.", verbose_name="Резюме във футъра")),
                        ("address_line", models.CharField(default="кв. Враждебна, ул. „8-ма“ 47", max_length=220, verbose_name="Адрес")),
                        ("city", models.CharField(default="София", max_length=120, verbose_name="Град")),
                        ("postal_code", models.CharField(blank=True, default="1839", max_length=20, verbose_name="Пощенски код")),
                        ("phone_primary", models.CharField(default="+359 88 000 0000", max_length=64, verbose_name="Основен телефон")),
                        ("phone_secondary", models.CharField(blank=True, max_length=64, verbose_name="Допълнителен телефон")),
                        ("email", models.EmailField(default="hello@example.bg", max_length=254, verbose_name="Имейл")),
                        ("working_hours_summary", models.CharField(default="Понеделник до неделя, 10:00 - 20:00", max_length=160, verbose_name="Резюме на работното време")),
                        ("map_embed_url", models.URLField(blank=True, help_text="OpenStreetMap или Google Maps embed адрес.", verbose_name="Вграден адрес за карта")),
                        ("copyright_notice", models.CharField(default="© Chitalishte Connect. Демонстрационна инсталация с оригинално примерно съдържание.", max_length=220, verbose_name="Авторски текст")),
                        ("cookie_banner_title", models.CharField(default="Настройки за бисквитки", max_length=120, verbose_name="Заглавие на банера за бисквитки")),
                        ("cookie_banner_text", models.TextField(default="Използваме само необходимите бисквитки по подразбиране. Можете да приемете и допълнителни аналитични бисквитки или да прочетете подробностите в правните страници.", verbose_name="Текст на банера за бисквитки")),
                    ],
                    options={
                        "verbose_name": "Глобални настройки",
                        "verbose_name_plural": "Глобални настройки",
                        "db_table": "cms_sitesettings",
                    },
                ),
                migrations.CreateModel(
                    name="LocationHour",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("weekday", models.IntegerField(choices=[(0, "Понеделник"), (1, "Вторник"), (2, "Сряда"), (3, "Четвъртък"), (4, "Петък"), (5, "Събота"), (6, "Неделя")], verbose_name="Ден")),
                        ("open_time", models.TimeField(blank=True, null=True, verbose_name="Отваря")),
                        ("close_time", models.TimeField(blank=True, null=True, verbose_name="Затваря")),
                        ("is_closed", models.BooleanField(default=False, verbose_name="Почивен ден")),
                        ("note", models.CharField(blank=True, max_length=120, verbose_name="Бележка")),
                        ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="hours", to="core.location")),
                    ],
                    options={
                        "verbose_name": "Работно време",
                        "verbose_name_plural": "Работно време",
                        "db_table": "cms_locationhour",
                        "ordering": ["weekday"],
                        "unique_together": {("location", "weekday")},
                    },
                ),
            ],
        ),
        migrations.AddField(
            model_name="footerlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footerlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seo_title",
            field=models.CharField(blank=True, help_text="По желание заменя стандартното заглавие в търсачки и споделяне.", max_length=160, verbose_name="SEO заглавие"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seo_description",
            field=models.TextField(blank=True, help_text="Кратко описание за търсачки, социални мрежи и линк превюта.", verbose_name="SEO описание"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seo_image",
            field=models.ImageField(blank=True, help_text="Използва се при споделяне в социални мрежи, когато има нужда от отделно изображение.", null=True, upload_to="seo/", verbose_name="SEO изображение"),
        ),
    ]
