# Generated by Django 5.2.12 on 2026-03-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_notice',
            field=models.CharField(default='© Chitalishte Connect. Всички права запазени.', max_length=220, verbose_name='Авторски текст'),
        ),
    ]
