# Generated by Django 5.2.12 on 2026-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sitesettings_copyright_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_intro',
            field=models.TextField(blank=True, default='Всички публични контакти са събрани на едно място, заедно с карта, работно време и директен вход за въпроси.', verbose_name='Увод на контактната страница'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_title',
            field=models.CharField(default='Контакти', max_length=160, verbose_name='Заглавие на контактната страница'),
        ),
    ]
