# Generated by Django 5.2.12 on 2026-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_contact_page_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours_summary',
            field=models.CharField(default='Понеделник - петък, 09:00 - 18:00', max_length=160, verbose_name='Резюме на работното време'),
        ),
    ]
