# Generated by Codex on 2026-04-13

from django.db import migrations


FACEBOOK_PAGE_URL = "https://www.facebook.com/profile.php?id=61550898774893"


def add_facebook_footer_link(apps, schema_editor):
    FooterLink = apps.get_model("core", "FooterLink")
    FooterLink.objects.get_or_create(
        url=FACEBOOK_PAGE_URL,
        defaults={
            "title": "Facebook",
            "open_in_new_tab": True,
            "sort_order": 7,
            "is_published": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_sitesettings_working_hours_summary"),
    ]

    operations = [
        migrations.RunPython(add_facebook_footer_link, migrations.RunPython.noop),
    ]
