# Generated by Codex on 2026-04-13

from django.db import migrations, models


NEW_COPYRIGHT_NOTICE = '© 2026 Народно читалище „Св. св. Кирил и Методий – 1926“. Всички права запазени.'
OLD_COPYRIGHT_NOTICES = [
    "© Chitalishte Connect. Демонстрационна инсталация с оригинално примерно съдържание.",
    "© Chitalishte Connect. Всички права запазени.",
]


def update_copyright_notice(apps, schema_editor):
    SiteSettings = apps.get_model("core", "SiteSettings")
    SiteSettings.objects.filter(copyright_notice__in=OLD_COPYRIGHT_NOTICES).update(
        copyright_notice=NEW_COPYRIGHT_NOTICE
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_facebook_footer_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="copyright_notice",
            field=models.CharField(
                default=NEW_COPYRIGHT_NOTICE,
                max_length=220,
                verbose_name="Авторски текст",
            ),
        ),
        migrations.RunPython(update_copyright_notice, migrations.RunPython.noop),
    ]
