# Generated by Django 5.2.12 on 2026-04-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_default_copyright_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='OpenStreetMap или Google Maps embed адрес.', max_length=1200, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, help_text='OpenStreetMap или Google Maps embed адрес.', max_length=1200, verbose_name='Вграден адрес за карта'),
        ),
    ]
