# Generated by Django 5.2.12 on 2026-04-18 14:33

from django.db import migrations, models


def copy_primary_location_to_site_settings(apps, schema_editor):
    SiteSettings = apps.get_model('core', 'SiteSettings')
    Location = apps.get_model('core', 'Location')

    location = (
        Location.objects.filter(is_published=True, is_primary=True)
        .order_by('-is_primary', 'sort_order', 'name')
        .first()
        or Location.objects.filter(is_published=True)
        .order_by('-is_primary', 'sort_order', 'name')
        .first()
        or Location.objects.order_by('-is_primary', 'sort_order', 'name').first()
    )
    if not location:
        return

    site_settings = SiteSettings.objects.first() or SiteSettings()
    site_settings.location_name = location.name
    site_settings.location_short_description = location.short_description
    site_settings.location_access_notes = location.access_notes
    site_settings.address_line = location.address_line
    site_settings.city = location.city
    site_settings.postal_code = location.postal_code
    if location.phone:
        site_settings.phone_primary = location.phone
    if location.email:
        site_settings.email = location.email
    if location.map_embed_url:
        site_settings.map_embed_url = location.map_embed_url
    site_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_location_map_embed_url_and_more'),
        ('inquiries', '0003_remove_inquirysubmission_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationhour',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='locationhour',
            name='location',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_access_notes',
            field=models.TextField(blank=True, verbose_name='Допълнителна информация за достъп'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_name',
            field=models.CharField(default='Основна база', max_length=160, verbose_name='Име на локацията'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_short_description',
            field=models.TextField(blank=True, verbose_name='Кратко описание на локацията'),
        ),
        migrations.RunPython(copy_primary_location_to_site_settings, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationHour',
        ),
    ]
